# -*- coding: utf-8 -*-
"""AI chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbOhYXqdyRSBZiLbOJzq53f6J-0HRnb7
"""

from openai import OpenAI

def chat_with_ai():
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key="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",
    )

    conversation_history = []
    print("ChatGPT-like bot: Type 'exit' to end the chat.")

    while True:
        user_input = input("You: ")
        if user_input.lower() == "exit":
            break

        conversation_history.append({"role": "user", "content": user_input})

        try:
            completion = client.chat.completions.create(
                extra_headers={
                    "HTTP-Referer": "<YOUR_SITE_URL>",
                    "X-Title": "<YOUR_SITE_NAME>",
                },
                model="deepseek/deepseek-r1:free",
                messages=conversation_history,
                stream=True
            )

            print("AI:", end=" ")
            response_text = ""
            for chunk in completion:
                if chunk.choices and chunk.choices[0].delta and hasattr(chunk.choices[0].delta, 'content'):
                    text = chunk.choices[0].delta.content
                    print(text, end="", flush=True)
                    response_text += text
            print()

            conversation_history.append({"role": "assistant", "content": response_text})

        except Exception as e:
            print("Error:", e)

if __name__ == "__main__":
    chat_with_ai()